[versions]
accompanist = "0.36.0"
activity-compose = "1.12.1"
android_tools = "8.13.2"
androidannotations = "4.8.0"
appcompat = "1.7.1"
biometric = "1.1.0"
collection-ktx = "1.5.0"
commons-io = "2.21.0"
core-ktx = "1.17.0"
datastore = "1.2.0"
detekt = "1.23.8"
glide = "5.0.5"
glide-compose = "1.0.0-beta08"
kotlin = "2.2.21"
kotlinx-datetime = "0.7.1"
workmanager = "2.11.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidannotations-api = { module = "org.androidannotations:androidannotations-api", version.ref = "androidannotations" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "collection-ktx" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-preferences-rx = { module = "androidx.datastore:datastore-preferences-rxjava3", version.ref = "datastore" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
eventbus = { module = "org.greenrobot:eventbus", version = "3.3.1" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glide-compose" }
google-play-base = { module = "com.google.android.gms:play-services-base", version = "18.9.0" }
google-play-drive = { module = "com.google.android.gms:play-services-drive", version = "17.0.0" }
google-play-plus = { module = "com.google.android.gms:play-services-plus", version = "17.0.0" }
java-collections = { module = "net.sf.trove4j:core", version = "3.1.0" }
koala-chart = { module = "io.github.koalaplot:koalaplot-core", version = "0.10.3" }
koin-bom = { module = "io.insert-koin:koin-bom", version = "4.1.1" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-android-compat = { module = "io.insert-koin:koin-android-compat" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
legacy-support = { module = "androidx.legacy:legacy-support-v4", version = "1.0.0" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.10.0" }
materialdatetimepicker = { module = "com.wdullaer:materialdatetimepicker", version = "4.2.3" }
okio = { module = "com.squareup.okio:okio", version = "3.16.4" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.3.2" }
reactive-streams = { module = "org.reactivestreams:reactive-streams", version = "1.0.4" }
rximagepicker = { module = "com.github.MLSDev:RxImagePicker", version = "master" }
rxjava2-rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version = "2.1.1"}
rxjava2-rxjava = { module = "io.reactivex.rxjava2:rxjava", version = "2.2.21"}
rxjava3-bridge = { module = "com.github.akarnokd:rxjava3-bridge", version = "3.0.2" }
rxjava3-rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version = "3.0.2" }
rxjava3-rxjava = { module = "io.reactivex.rxjava3:rxjava", version = "3.1.12" }
sqlite-ktx = { module = "androidx.sqlite:sqlite-ktx", version = "2.6.2" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
workmanager = { module = "androidx.work:work-runtime", version.ref = "workmanager" }
workmanager-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android_tools" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.4" }
